api_platform:    
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
        jsonhal: ['application/hal+json']


when@prod:
    api_platform:
        enable_docs: false
        enable_entrypoint: false